# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 17:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20160702_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='key_expires',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 17, 2, 31, 337486)),
        ),
    ]
