# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 18:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, unique=True)),
                ('email', models.SlugField(unique=True)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('mobile_number', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
